---
- hosts: 001
  become_user: root
  become: yes

  tasks:
    - name: Take rpm client zabbix.
      command: /app/scripts/deploy-static.sh /app/bkoffice/files/BKOfficeFrontEnd.tar.gz
      ignore_errors: yes  

    - name: Install agent zabbix.
      command: /app/scripts/deploy.sh /app/bkoffice/files/BKOfficeAPI.war
      
    - name: Run command
      command: /app/scripts/deploy.sh /app/bkoffice/files/BKOfficeFrontEnd.war

    - name: Setting on system
      command: SYSTEMCLT STOP TOMCAT  K&YZT~v{f5t)w#9a